name: Deploy to firebase and Create release

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Firebase Login
        run: |
          npm install -g firebase-tools
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase
        run: |
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"  

      - name: Create Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with: 
          files: ./*
          tag_name: v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
