name: Deploy to preview channel on firebase

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
      
      - name: Build And lint
        run: npm run build

      - name: Firebase Login
        run: |
          npm install -g firebase-tools
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase
        run: |
          firebase hosting:channel:deploy preview --token "${{ secrets.FIREBASE_TOKEN }}"  
